
import java.awt.CardLayout;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Della Novia Ramadhan
 */
public class TampilGambar extends javax.swing.JFrame {

    /**
     * Creates new form TampilGambar
     */
    public TampilGambar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonLayout = new javax.swing.JPanel();
        jakartaButton = new javax.swing.JButton();
        istanbulButton = new javax.swing.JButton();
        tokyoButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        imageLayout = new javax.swing.JPanel();
        jakartaLabel = new javax.swing.JLabel();
        istanbulLabel = new javax.swing.JLabel();
        tokyoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jakartaButton.setBackground(new java.awt.Color(255, 153, 153));
        jakartaButton.setText("Jakarta");
        jakartaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jakartaButtonActionPerformed(evt);
            }
        });
        buttonLayout.add(jakartaButton);

        istanbulButton.setBackground(new java.awt.Color(153, 255, 153));
        istanbulButton.setText("Istanbul");
        istanbulButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                istanbulButtonActionPerformed(evt);
            }
        });
        buttonLayout.add(istanbulButton);

        tokyoButton.setBackground(new java.awt.Color(204, 153, 255));
        tokyoButton.setText("Tokyo");
        tokyoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tokyoButtonActionPerformed(evt);
            }
        });
        buttonLayout.add(tokyoButton);

        exitButton.setBackground(new java.awt.Color(255, 51, 51));
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        buttonLayout.add(exitButton);

        getContentPane().add(buttonLayout, java.awt.BorderLayout.PAGE_START);

        imageLayout.setLayout(new java.awt.CardLayout());

        jakartaLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ridho Okta Pawarestu\\OneDrive\\Pictures\\jakarta2.jpg")); // NOI18N
        imageLayout.add(jakartaLabel, "0");

        istanbulLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ridho Okta Pawarestu\\OneDrive\\Pictures\\istanbul.jpg")); // NOI18N
        imageLayout.add(istanbulLabel, "1");

        tokyoLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ridho Okta Pawarestu\\OneDrive\\Pictures\\tokyo2.jpg")); // NOI18N
        imageLayout.add(tokyoLabel, "2");

        getContentPane().add(imageLayout, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void jakartaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jakartaButtonActionPerformed
        CardLayout c1 = (CardLayout) (imageLayout.getLayout());
        c1.show(imageLayout, "0");
    }//GEN-LAST:event_jakartaButtonActionPerformed

    private void istanbulButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_istanbulButtonActionPerformed
        CardLayout c1 = (CardLayout) (imageLayout.getLayout());
        c1.show(imageLayout, "1");
    }//GEN-LAST:event_istanbulButtonActionPerformed

    private void tokyoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tokyoButtonActionPerformed
        CardLayout c1 = (CardLayout) (imageLayout.getLayout());
        c1.show(imageLayout, "2");
    }//GEN-LAST:event_tokyoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TampilGambar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonLayout;
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel imageLayout;
    private javax.swing.JButton istanbulButton;
    private javax.swing.JLabel istanbulLabel;
    private javax.swing.JButton jakartaButton;
    private javax.swing.JLabel jakartaLabel;
    private javax.swing.JButton tokyoButton;
    private javax.swing.JLabel tokyoLabel;
    // End of variables declaration//GEN-END:variables
}
